### ISSUE TITLE
NES loader not detected in IDA Pro 7.3.190614

### ISSUE THREAD

**Issue by evandrix** [patois/nesldr#1]
already placed in [%idadir%/loaders/nes.ldw](%idadir%/loaders/nes.ldw), but still not detected

**Comment by patois** [comment]
Sorry, the loader was written for a very early version of IDA. The source and binaries are most probably not compatible with recent versions of IDA, sorry for that.

**Comment by patois** [comment]
I've just discovered the following repository which has the NES loader ported to recent IDA versions using IDAPython. It works on my 7.4, maybe you want to give it a try:

https://github.com/Jinmo/nesldr-py

I will discontinue development of this project and close this issue.
